pipeline {
    agent {
        docker {
	    image 'python:2.7.16-slim'
	    args '--user root'
            }
    }
    stages {
        stage('Build') { 
	    when {
		changeset "**/vote/**"
	    }
            steps {
                echo 'Compiling vote app'
		dir('vote'){
		    sh 'pip install -r requirements.txt' 
		}
                echo '### FINISHED BUILDING ###'
            }
        }
        stage('Test') { 
	    when {
		changeset "**/vote/**"
	    }
            steps {
		dir('vote'){
		    sh 'nosetests -v'
		}
                echo '### FINISHED TESTING ###'
            }
        }

        stage('Docker-package') {
            agent any
            when {
                changeset "**/vote/**"
                branch 'master'
            }
            steps {
                echo 'Starting PACKAGING the app with docker.....'
                script{
                  docker.withRegistry('https://index.docker.io/v1/', 'dockerlogin') {
                     def workerImage = docker.build("mcberra/vote:v${env.BUILD_ID}", "./vote")
                     workerImage.push()
                     workerImage.push("${env.BRANCH_NAME}")
                  }
                }
            }
        }
    }

    post { 
        always { 
            echo 'This pipeline run is completed!'
        }
    }
}
