pipeline {
    agent none

    stages {

        stage('Build') {
 
          agent {
            docker {
	      image 'python:2.7.16-slim'
	      args '--user root'
                }
              }

            steps {
                echo 'Compiling vote app'
		dir('vote'){
		    sh 'pip install -r requirements.txt' 
		}
                echo '### FINISHED BUILDING ###'
            }
        }

        stage('Test') {
            agent {
              docker {
	        image 'python:2.7.16-slim'
	        args '--user root'
              }
            } 
            steps {

                echo '###  TESTING VOTE APP ###'
		dir('vote'){
		    sh 'pip install -r requirements.txt' 
		    sh 'nosetests -v'
		}
            }
        }

    }

    post { 
        always { 
            echo 'This pipeline run is completed!'
        }
    }
}
