pipeline {
    agent any
    tools {
        maven 'Maven-3.6.1' 
    }
    stages {
        stage('Build') { 
            steps {
                echo 'Starting BUILD.....'
                echo 'Compiling worker app'
		dir('worker'){
		    sh 'mvn compile' 
		}
                echo '### FINISHED BUILDING ###'
            }
        }
        stage('Test') { 
            steps {
                echo 'Starting TEST.....'
		dir('worker'){
		    sh 'mvn clean test' 
		}
                echo '### FINISHED TESTING ###'
            }
        }
        stage('Package') { 
            steps {
                echo 'Starting PACKGING.....'
		dir('worker'){
		    sh 'mvn package -DskipTests'
		}
                echo '### FINISHED PACKAGING ###' 
            }
        }
    }
        post { 
            always { 
		archiveArtifacts artifacts: '**/target/*.jar', fingerprint: true
                echo 'This pipeline run is completed!'
        }
    }
}
